### ISSUE TITLE
Can't upload a zip file

### ISSUE THREAD

**Issue by knmnyn** [WING-NUS/SSID#6] opened 2013-03-13 00:53 UTC
Hi:

I've tried to add a new assignment, but the system refuses to take zipfiles as input.  I've tried multiple zipfiles (all seem to be in good shape), but none are accepted.  Did something change in the production system? 

New Assignment
1 error prohibited this assignment from being saved:

```
File for upload must be a zip file
```

**Comment by Riyas97** [comment] 2020-09-03 15:16
Hi. Looking at it, being unable to upload valid zip files seems to have been rectified in #37. But to further verify it, it would be nice if I can get access to the files that created this error in the first place, provided you still have them. If not, I guess we can close this issue for now and monitor whether people are having trouble uploading their zip files. Thanks.

**Comment by Riyas97** [comment] 2021-02-09 08:47
Seems like this is a duplicate of #31. So, I am closing this.

**Closed by Riyas97** 2021-02-09 08:47 UTC
Labels: bug, priority-high
